language: node_js
node_js:
- '7'
cache: yarn
before_install: npm i -g yarn
install: yarn install
script: yarn run build
deploy:
  skip_cleanup: true
  provider: npm
  email: josemoreiravarzim@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: get-reformulate/reformulate
